### ISSUE TITLE
Might be good to note there cannot be any spaces in ENTIRE file path

### ISSUE THREAD

**Issue by clairemerriman** [XimeraProject/ximeraManuals#8]
If the repo is cloned into a location with spaces or special characters anywhere in the file path, xake will not compile.

For example, placing the repo in a Google Drive folder will introduce spaces and special characters to the file path. This prevents the files from compiling (to PDF or HTML), even if all of the files inside the repo are named correctly.

https://github.com/XimeraProject/ximeraManuals/blob/8ad3f7ff8e698848353ada8b2bd65483a169fd76/gettingWorkDone/githubSetup.tex#L28

**Comment by bartsnapp** [comment]
Addressed this and fixed additional typos. Thanks!
